Refactor CodeLocation and type its properties.
angr/angr pull request #2408
Opened 2020-12-03 17:55 UTC by ltfish

2020-12-03 18:01 UTC, Pamplemousse reviewed
Looks much better!

I have a question / remark though: 
Should context accept `None` as a value at all? Shouldn't its "default" be `()` (`None` as parameter of `__init__`, but set to `()` during instanciation)?

2020-12-03 19:54 UTC, ltfish commented on angr/code_location.py
> +        # sanitization: if context is an empty tuple, we store a None instead
One less object.

2020-12-03 19:59 UTC, ltfish commented
> 
> 
> Looks much better!
> 
> I have a question / remark though:
> Should context accept `None` as a value at all? Shouldn't its "default" be `()` (`None` as parameter of `__init__`, but set to `()` during instanciation)?

I feel we should allow context-less `CodeLocation` to exist.

2020-12-03 20:12 UTC, Pamplemousse commented
> I feel we should allow context-less CodeLocation to exist.

Yeah, I tend to agree.
However, because `()` is stored as `None`, there is no distinction possible between "empty context" and "context-less"...

2020-12-03 21:01 UTC, ltfish commented
> > I feel we should allow context-less CodeLocation to exist.
> 
> Yeah, I tend to agree.
> However, because `()` is stored as `None`, there is no distinction possible between "empty context" and "context-less"...

So the problem seems to be that we are passing in `None` at places where we should actually be passing in empty tuples. I’ll look into this issue.

2020-12-04 18:27 UTC, Pamplemousse requested changes

2020-12-04 18:27 UTC, Pamplemousse commented on angr/code_location.py
> +        # sanitization: if context is an empty tuple, we store a None instead
This comment is not needed anymore!

2020-12-04 18:34 UTC, ltfish commented on angr/code_location.py
> +        # sanitization: if context is an empty tuple, we store a None instead
Fixed!

2020-12-04 18:51 UTC, Pamplemousse approved these changes

2020-12-04 23:56 UTC, merged