Remove nose imports
angr/angr pull request #2959
Opened 2021-11-03 22:16 UTC by Adersh97

2021-11-04 02:42 UTC, twizmwazin reviewed
So typically when using unittest's asserts, it is in methods of existing `TestCase` objects. For tests that are standalone functions, we either want to convert them to be methods of `TestCase` subclasses, or probably use the `assert` keyword instead.

2021-11-11 17:48 UTC, ltfish requested changes
I pointed out several prevalent mistakes. Please go through your PR and fix these issues accordingly. Thanks!

2021-11-11 17:48 UTC, ltfish commented on tests/analyses/reaching_definitions/test_subject.py
> +    assert (subject.type == SubjectType.Function)
Remove the surrounding parentheses please. It should be `assert subject.type == SubjectType.Function`.

2021-11-11 17:48 UTC, ltfish commented on tests/analyses/reaching_definitions/test_subject.py
> +    assert (subject.type == SubjectType.Block)
Same as above.

2021-11-11 17:48 UTC, ltfish commented on tests/analyses/reaching_definitions/test_subject.py
> +    assert flag
Let's not reimplement `assertRaises`. Can you rewrite this function to use `unittest.TestCase` so you can call `self.assertRaises()` there?

2021-11-11 17:48 UTC, ltfish commented on tests/test_argv.py
> +    assert b"Yan is a noob" in conc == True
`== True` is redundant. It should be `assert b"Yan is a noob" in conc`.

2021-11-15 20:25 UTC, twizmwazin requested changes
I left a bunch of inline comments for various issues. I tried to only leave one comment per type of issue per file, so please check if a problem exists multiple times within that file. Thank you!

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_stack_alignment.py
> +            assert st.solver.is_true(((st.regs.sp + cc.STACKARG_SP_DIFF) % cc.STACK_ALIGNMENT == 0))
Please preserve the message

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_state.py
> -    nose.tools.assert_raises(angr.errors.SimMergeError, lambda: a.copy().merge(b.copy()))
Looks like this got dropped without a replacement?

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_state.py
> +    assert len(simgr.errored) == 0
Please preserve the messages

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_tracer.py
> +    assert stdout_dump.startswith(b"\nWelcome to Palindrome Finder\n\n"                                                   b"\tPlease enter a possible palindrome: "
Formatting

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_types.py
> +    assert sig.arg_names == nsig.arg_names
Please preserve the message

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_unicorn.py
> +    assert sorted(pg.mp_deadended.posix.dumps(1).mp_items) == sorted((         b'Username: \nPassword: \nWelcome to the admin console, trusted user!\n',         b'Username: \nPassword: \nGo away!',
Formatting

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_variablerecovery.py
> +            assert the_var is not None
Please preserve the message

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_vex.py
> -
Looks like a few too many newlines were removed here

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_vfg.py
> +    assert set([ s.solver.eval_one(s.ip) for s in states ]) == {                                 stack_check_fail,                                 0x4005b4                             }
Formatting

2021-11-15 20:25 UTC, twizmwazin commented on tests/test_windows_stack_cookie.py
> -    nose.tools.assert_raises(TypeError, project.factory.blank_state, security_cookie_init=1)
This should be converted to unittest to use its equivalent.

2021-11-17 22:10 UTC, twizmwazin requested changes
Great progress! Please address the inline comments plus the CI failures.

2021-11-19 21:19 UTC, twizmwazin reviewed
Please be careful to make sure you resolve all of the git conflicts! In the future, we'll probably want to break massive PRs like this down in to more manageable chunks that can be merged more quickly to avoid conflicts.

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_cfg_thumb_firmware.py
> +    assert f2.returning
trailing whitespace

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_keystone.py
> +<<<<<<< HEAD
Looks like you missed a git conflict

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_scanf.py
> +<<<<<<< HEAD
Another git conflict

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_spiller.py
> +<<<<<<< HEAD
git conflict

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_sscanf.py
> +<<<<<<< HEAD
git conflict

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_unicorn.py
> +<<<<<<< HEAD
git conflicts, quite a few in this file

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_vault.py
> +<<<<<<< HEAD
git conflict

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_vfg.py
> +<<<<<<< HEAD
git conflict

2021-11-19 21:19 UTC, twizmwazin commented on tests/test_windows_stack_cookie.py
> +<<<<<<< HEAD
git conflict

2021-11-25 02:25 UTC, twizmwazin approved these changes
LGTM once the CI passes

2021-11-25 02:25 UTC, twizmwazin commented on tests/test_keystone.py
> +            yield run_keystone, arch_name
I believe this should be `self.run_keystone`, and that is what is causing the weird CI failure

2021-12-06 23:56 UTC, twizmwazin requested changes
I went through the past comments to double check that the issues were addressed, a few were missed. Please mark the comments resolved once they are fixed, and then this will LGTM.

2021-12-28 16:01 UTC, merged

2021-12-28 16:12 UTC, twizmwazin commented
Thanks!