Removed generators in test_calling_convention_analysis.py
angr/angr pull request #3104
Opened 2022-01-26 07:30 UTC by mohitrpatil

2022-01-27 22:21 UTC, rhelmot approved these changes

2022-01-27 22:43 UTC, ltfish commented on tests/test_calling_convention_analysis.py
> +            self._run_fauxware, arch, lst
Seems like a useless statement to me.

2022-01-29 22:58 UTC, twizmwazin requested changes

2022-01-29 22:58 UTC, twizmwazin commented on tests/test_calling_convention_analysis.py
> +        for arch , lst in args.items():
Since the dict only has a single item in it, let's remove this and pass the arguments directly.

2022-01-30 03:31 UTC, twizmwazin reviewed
Please fix the lint and I'll hit merge! Looks like you might have removed the `@requires_binaries_private` and forgot to re-add it.

2022-01-30 04:42 UTC, merged

2022-01-30 04:44 UTC, twizmwazin commented
Thanks!