Added Chroot SimProcedures
angr/angr pull request #3449
Opened 2022-07-23 04:20 UTC by Aydalanche

2022-07-25 16:22 UTC, ltfish requested changes

2022-07-25 16:22 UTC, ltfish commented on angr/procedures/posix/chroot.py
> +        return 0
Please add a blank line at the end of the file.

2022-07-25 16:22 UTC, ltfish commented on tests/test_chroot.py
> +    test_chroot()
Same here. A blank line at the end of the file.

2022-07-25 16:22 UTC, ltfish commented on tests/test_chroot.py
> +def test_chroot():
Please switch to `unittest.TestCase`-style test cases.

2022-07-25 16:22 UTC, ltfish commented on tests/test_chroot.py
> +        print("Error while trying to open the file")
A test case should fail by raising exceptions or assertion failures when success conditions are not met.

2022-07-25 22:47 UTC, Aydalanche commented
I updated the code to add what you requested and I removed the try and except part of the code from the test file so that it will actually fail if the file or filesystem can't be found.

2022-07-26 07:14 UTC, ltfish approved these changes

2022-07-26 07:14 UTC, merged

2022-07-26 07:14 UTC, ltfish commented
Merged. Thanks!