Disassembly: add arm32 support
angr/angr pull request #3749
Opened 2023-01-14 12:52 UTC by xxr0ss

- Simplified arm64 instructon dissection
- Removed hard-coded arch strings
- Tests

2023-01-16 06:35 UTC, xxr0ss commented
I'll rebase this branch when PR https://github.com/angr/angr/pull/3750 is merged

2023-01-16 20:57 UTC, ltfish commented on tests/test_disassembly.py
> +    def test_arm_dissect_instructions(self):
Why are you changing `arm64` to `arm`?

2023-01-16 20:57 UTC, ltfish commented on tests/test_disassembly.py
> +            archinfo.ArchAArch64(),
IMO this change is not necessary. angr (in fact, archinfo) should be able to convert "AArch64" to `archinfo.ArchAArch64`.

2023-01-16 20:58 UTC, ltfish commented on tests/test_disassembly.py
> +        assert rendered_insns[1].endswith('^')
Thanks for adding an ARM-specific test case. Can you please separate the AArch64 test case and this ARM test case into two methods?

2023-01-16 20:58 UTC, ltfish commented on tests/test_disassembly.py
> +            archinfo.ArchMIPS32(),
This change is unnecessary.

2023-01-16 20:59 UTC, ltfish requested changes
Please take a look at my comments above.

2023-01-17 03:06 UTC, xxr0ss commented
@ltfish Thanks for reviewing my code, I'll fix these soon

2023-01-17 06:04 UTC, xxr0ss reviewed
Done

2023-01-17 06:06 UTC, xxr0ss reviewed
Ready to merge

2023-01-17 07:32 UTC, ltfish approved these changes

2023-01-17 07:32 UTC, merged

2023-01-17 07:32 UTC, ltfish commented
Thank you!

2023-01-17 07:47 UTC, xxr0ss commented
Happy to help! @ltfish BTW https://github.com/angr/angr/issues/3485, https://github.com/angr/angr/pull/3621 can be closed