[WIP] Added feature: completely abolished redundant else scope
angr/angr pull request #4004
Opened 2023-06-20 20:54 UTC by intranautic

2023-06-20 21:18 UTC, mahaloz requested changes

2023-06-20 21:18 UTC, mahaloz commented on angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
> +            if last_block and not [*self._graph.successors(last_block)]:
Don't do this unpacking. Explicitly convert generators to lists if you are using it like a list.

2023-06-20 21:18 UTC, mahaloz commented on angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
> +    DESCRIPTION = "there is no salvation for the wicked, free will is an illusion"
Update this.

2023-06-20 21:18 UTC, mahaloz commented on angr/analyses/decompiler/optimization_passes/__init__.py
> +from .flip_boolean_cmp import FlipBooleanCmp
Put a newline after this line

2023-06-20 21:18 UTC, mahaloz commented on angr/analyses/decompiler/structured_codegen/c.py
> +            last_block = None
Make this entire block a boolean method in `c.py` (put it near the to). Maybe call it:
```python
def is_simple_return_node(node: Union[ailment.Block, SequenceNode]) -> bool:
    ...
```

2023-06-20 23:26 UTC, ltfish commented on angr/analyses/decompiler/decompiler.py
> +            clinic=clinic,
Let's pass in the output that Clinic generates, instead of passing in the entire Clinic instance.

2023-06-21 05:00 UTC, mahaloz commented
@intranautic don't forget to do two more things:
1. Add Decompiler option so this can be disabled (and test it)
2. Add a testcase for `od.o`. This will require you to make a second PR in the binaries repo, which I can show you how to do.

2023-06-21 22:42 UTC, mahaloz approved these changes
Includes a new test case for this feature! Nice job!

2023-06-21 23:10 UTC, ltfish commented on angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
> +    ARCHES = ["X86", "AMD64"]
Why are we limiting architectures to x86 and amd64? Also why are we limiting platforms? This seems to be a generic optimization for all architectures and platforms.

2023-06-21 23:11 UTC, ltfish requested changes
Please remove arch and platform limits or justify them.

2023-06-22 07:31 UTC, ltfish approved these changes

2023-06-22 07:32 UTC, merged